### ISSUE TITLE
sensitive data public?

### ISSUE THREAD

**Issue by mkoelewijn** [Daniel-WWU-IT/sciencemesh-wwu#5]
Hi, 

We found out that there is a SQL database backup public that contains data of one of our users. This SQL backup should not be public?

https://github.com/Daniel-WWU-IT/sciencemesh-wwu/blob/59d3bbe11900257c196cb87b272d300dc84d355d/gocdb/backup/gocdb-2020-11-23.sql

**Comment by Daniel-WWU-IT** [comment]
Which data are you referring to?

**Comment by mkoelewijn** [comment]
The account names and email addresses (and other fields belonging to the accounts). For instance: https://github.com/Daniel-WWU-IT/sciencemesh-wwu/blob/59d3bbe11900257c196cb87b272d300dc84d355d/gocdb/backup/gocdb-2020-11-23.sql#L937

**Comment by Daniel-WWU-IT** [comment]
No, you are misinterpreting the information. But we will put this SQL file into a password protected zip so that it can't be accessed publicly.
